# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Fpy ====================

Fpy:
  - FpyEmulator
  - Emulator
  - Error
  - Optimization

FpyHeartbeat:
  - Scheduler
  - Interval

# ==================== Farm ====================

FpyMain:
  - Scheduler
  - Team
  - Apple
  - Limit
  - Interval

# ==================== Daily ====================

FpyDailyFpSummon:
  - Scheduler

# ==================== Tool ====================

FpyBattle: []

FpyBenchmark:
  - Benchmark

FpyCall:
  - Call
